language: node_js
node_js:
  - node
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: reorginization
script: 
  - npm run build
